function sma = BuildStateMachine(S, stimulusDuration, iti, punishITI, target, probeType, optoType)
% Build one AV discrimination trial with moving spouts and side choice.
if nargin < 7 || isempty(optoType)
    optoType = zeros(5, 1);
end
opto = OptoControl('actions', S, optoType, stimulusOptoDuration(S, stimulusDuration, probeType), target.ValveTime, punishITI);
sma = NewStateMatrix();
for i = 1:numel(opto.Timers)
    timer = opto.Timers(i);
    sma = SetGlobalTimer(sma, ...
        'TimerID', timer.TimerID, ...
        'Duration', timer.Duration, ...
        'OnsetDelay', timer.OnsetDelay, ...
        'Channel', timer.Channel, ...
        'OnLevel', timer.OnLevel, ...
        'OffLevel', timer.OffLevel, ...
        'Loop', timer.Loop, ...
        'LoopInterval', timer.LoopInterval, ...
        'SendGlobalTimerEvents', 1, ...
        'GlobalTimerEvents', 1, ...
        'OffsetValue', 0);
end

if S.GUI.StimulusMode == 2
    videoSoftCode = 26;
else
    videoSoftCode = 25;
end

if S.GUI.StimulusMode == 1
    audioAction = {};
else
    audioAction = {'HiFi1', ['P', 4]};
end

sma = AddState(sma, 'Name', 'Start', ...
    'Timer', 0.068, ...
    'StateChangeConditions', {'Tup', 'VisStimTrigger'}, ...
    'OutputActions', [{'HiFi1', '*', 'BNC1', 1} opto.StartActions]);

sma = AddState(sma, 'Name', 'VisStimTrigger', ...
    'Timer', 0, ...
    'StateChangeConditions', {'Tup', 'AudStimTrigger'}, ...
    'OutputActions', {'SoftCode', videoSoftCode});

sma = AddState(sma, 'Name', 'AudStimTrigger', ...
    'Timer', stimulusDuration, ...
    'StateChangeConditions', {'Tup', 'StimulusDone'}, ...
    'OutputActions', [audioAction opto.StimulusStart]);

sma = AddState(sma, 'Name', 'StimulusDone', ...
    'Timer', 0, ...
    'StateChangeConditions', {'Tup', nextAfterStimulus(probeType)}, ...
    'OutputActions', {'SoftCode', 254, 'HiFi1', 'X'});

sma = AddState(sma, 'Name', 'SpoutInDelay', ...
    'Timer', S.GUI.SpoutInDelay_s, ...
    'StateChangeConditions', {'Tup', 'SpoutIn'}, ...
    'OutputActions', {});

sma = AddState(sma, 'Name', 'SpoutIn', ...
    'Timer', S.GUI.ServoMoveDelay_s, ...
    'StateChangeConditions', {'Tup', nextAfterSpoutIn(S)}, ...
    'OutputActions', {'SoftCode', 9});

sma = AddState(sma, 'Name', 'ProbeSpoutIn', ...
    'Timer', S.GUI.ServoMoveDelay_s, ...
    'StateChangeConditions', {'Tup', 'ProbeChoiceWindow'}, ...
    'OutputActions', {'SoftCode', 9});

sma = AddState(sma, 'Name', 'ProbeChoiceWindow', ...
    'Timer', S.GUI.ChoiceWindow_s, ...
    'StateChangeConditions', {'Tup', 'ServoOut'}, ...
    'OutputActions', opto.ChoiceStart);

if S.GUI.TrainingMode == 1
    sma = addNaiveStates(sma, S, target, opto);
else
    sma = addTrainedStates(sma, S, target, opto);
end

sma = AddState(sma, 'Name', 'PreRewardDelay', ...
    'Timer', S.GUI.PreRewardDelay_s, ...
    'StateChangeConditions', {'Tup', 'Reward'}, ...
    'OutputActions', [opto.ChoiceOff opto.RewardStart]);

sma = AddState(sma, 'Name', 'Reward', ...
    'Timer', target.ValveTime, ...
    'StateChangeConditions', {'Tup', 'PostRewardDelay'}, ...
    'OutputActions', {target.Valve, 1});

sma = AddState(sma, 'Name', 'PostRewardDelay', ...
    'Timer', S.GUI.PostRewardDelay_s, ...
    'StateChangeConditions', {'Tup', 'ServoOut'}, ...
    'OutputActions', opto.PostRewardStart);

sma = AddState(sma, 'Name', 'ServoOut', ...
    'Timer', S.GUI.ServoReturnTimeout_s, ...
    'StateChangeConditions', {'SoftCode2', 'ITI', 'Tup', 'ITI'}, ...
    'OutputActions', [{'SoftCode', 8} opto.AllOff]);

sma = AddState(sma, 'Name', 'ServoOutPunish', ...
    'Timer', S.GUI.ServoReturnTimeout_s, ...
    'StateChangeConditions', {'SoftCode2', 'PunishITI', 'Tup', 'PunishITI'}, ...
    'OutputActions', [{'SoftCode', 8} opto.AllOff]);

sma = AddState(sma, 'Name', 'PunishITI', ...
    'Timer', punishITI, ...
    'StateChangeConditions', {'Tup', 'ITI'}, ...
    'OutputActions', opto.PunishStart);

sma = AddState(sma, 'Name', 'ITI', ...
    'Timer', iti, ...
    'StateChangeConditions', {'Tup', '>exit'}, ...
    'OutputActions', [{'SoftCode', 254, 'HiFi1', 'X', 'BNC1', 0} opto.AllOff]);
end

function nextState = nextAfterStimulus(probeType)
if probeType == 1
    nextState = 'ITI';
elseif probeType == 2
    nextState = 'ProbeSpoutIn';
else
    nextState = 'SpoutInDelay';
end
end

function nextState = nextAfterSpoutIn(S)
if S.GUI.TrainingMode == 1
    nextState = 'NaiveReward';
else
    nextState = 'ChoiceWindow';
end
end

function sma = addNaiveStates(sma, S, target, opto)
sma = AddState(sma, 'Name', 'NaiveReward', ...
    'Timer', target.ValveTime, ...
    'StateChangeConditions', {'Tup', 'WaitForCorrectLick'}, ...
    'OutputActions', {target.Valve, 1});

sma = AddState(sma, 'Name', 'WaitForCorrectLick', ...
    'Timer', S.GUI.ChoiceWindow_s, ...
    'StateChangeConditions', {target.CorrectLick, 'PostRewardDelay', 'Tup', 'ServoOut'}, ...
    'OutputActions', opto.ChoiceStart);
end

function sma = addTrainedStates(sma, S, target, opto)
if S.GUI.AllowChangeMind
    wrongState = 'ChangeMindWindow';
else
    wrongState = 'ServoOutPunish';
end

sma = AddState(sma, 'Name', 'ChoiceWindow', ...
    'Timer', S.GUI.ChoiceWindow_s, ...
    'StateChangeConditions', {target.CorrectLick, 'PreRewardDelay', target.IncorrectLick, wrongState, 'Tup', 'ServoOutPunish'}, ...
    'OutputActions', opto.ChoiceStart);

sma = AddState(sma, 'Name', 'ChangeMindWindow', ...
    'Timer', S.GUI.ChangeMindWindow_s, ...
    'StateChangeConditions', {target.CorrectLick, 'PreRewardDelay', 'Tup', 'ServoOutPunish'}, ...
    'OutputActions', opto.ChoiceOff);
end

function duration = stimulusOptoDuration(S, stimulusDuration, probeType)
if probeType == 1
    duration = stimulusDuration;
elseif probeType == 2
    duration = stimulusDuration + S.GUI.ServoMoveDelay_s;
else
    duration = stimulusDuration + S.GUI.SpoutInDelay_s + S.GUI.ServoMoveDelay_s;
end
end
