function sma = BuildStateMachine(S, stimulusDuration, iti, punishITI, target, probeType, optoType)
% Build one AV discrimination trial with moving spouts and side choice.
if nargin < 7 || isempty(optoType)
    optoType = zeros(7, 1);
end
isNaive = S.GUI.TrainingMode == 1;
if isNaive
    % Naive trials never enter probe paths or configure opto timers/actions.
    probeType = 0;
    opto = noOptoActions;
else
    opto = OptoControl('actions', S, optoType, stimulusOptoDuration(S, stimulusDuration), target.ValveTime, punishITI);
end
sma = NewStateMatrix();
for i = 1:numel(opto.Timers)
    timer = opto.Timers(i);
    sma = SetGlobalTimer(sma, ...
        'TimerID', timer.TimerID, ...
        'Duration', timer.Duration, ...
        'OnsetDelay', timer.OnsetDelay, ...
        'Channel', timer.Channel, ...
        'OnLevel', timer.OnLevel, ...
        'OffLevel', timer.OffLevel, ...
        'Loop', timer.Loop, ...
        'LoopInterval', timer.LoopInterval, ...
        'SendGlobalTimerEvents', 1, ...
        'GlobalTimerEvents', 1, ...
        'OffsetValue', 0);
end

if S.GUI.StimulusMode == 2
    videoSoftCode = 26;
else
    videoSoftCode = 25;
end

if S.GUI.StimulusMode == 1
    audioAction = {};
else
    audioAction = {'HiFi1', ['P', 4]};
end

sma = AddState(sma, 'Name', 'Start', ...
    'Timer', 0.068, ...
    'StateChangeConditions', {'Tup', 'PreStimDelay'}, ...
    'OutputActions', [{'HiFi1', '*', 'BNC1', 1} opto.StartActions]);

sma = AddState(sma, 'Name', 'PreStimDelay', ...
    'Timer', S.GUI.PreStimDelay_s, ...
    'StateChangeConditions', {'Tup', 'VisStimTrigger'}, ...
    'OutputActions', opto.StimulusStart);

sma = AddState(sma, 'Name', 'VisStimTrigger', ...
    'Timer', 0, ...
    'StateChangeConditions', {'Tup', 'AudStimTrigger'}, ...
    'OutputActions', {'SoftCode', videoSoftCode});

sma = AddState(sma, 'Name', 'AudStimTrigger', ...
    'Timer', stimulusDuration, ...
    'StateChangeConditions', {'Tup', 'StimulusDone'}, ...
    'OutputActions', audioAction);

sma = AddState(sma, 'Name', 'StimulusDone', ...
    'Timer', 0, ...
    'StateChangeConditions', {'Tup', nextAfterStimulus(probeType)}, ...
    'OutputActions', {'SoftCode', 254, 'HiFi1', 'X'});

sma = AddState(sma, 'Name', 'SpoutInDelay', ...
    'Timer', S.GUI.SpoutInDelay_s, ...
    'StateChangeConditions', {'Tup', 'SpoutIn'}, ...
    'OutputActions', opto.SpoutInDelayStart);

sma = AddState(sma, 'Name', 'SpoutIn', ...
    'Timer', S.GUI.ServoMoveDelay_s, ...
    'StateChangeConditions', {'Tup', nextAfterSpoutIn(isNaive)}, ...
    'OutputActions', {'SoftCode', 9});

if ~isNaive
    sma = AddState(sma, 'Name', 'ProbeSpoutIn', ...
        'Timer', S.GUI.ServoMoveDelay_s, ...
        'StateChangeConditions', {'Tup', 'ProbeChoiceWindow'}, ...
        'OutputActions', {'SoftCode', 9});

    sma = AddState(sma, 'Name', 'ProbeChoiceWindow', ...
        'Timer', S.GUI.ChoiceWindow_s, ...
        'StateChangeConditions', {'Tup', 'ServoOut'}, ...
        'OutputActions', opto.SpoutInStart);
end
sma = addChoiceStates(sma, S, target, opto, isNaive);
sma = addPostLickDelayStates(sma, S, opto, isNaive);

if isNaive
    sma = addNaiveOutcomeStates(sma, target);
else
    sma = addTrainedOutcomeStates(sma, S, target, opto);
end

sma = AddState(sma, 'Name', 'PostRewardDelay', ...
    'Timer', S.GUI.PostRewardDelay_s, ...
    'StateChangeConditions', {'Tup', 'ServoOut'}, ...
    'OutputActions', opto.PostRewardStart);

sma = AddState(sma, 'Name', 'ServoOut', ...
    'Timer', S.GUI.ServoReturnTimeout_s, ...
    'StateChangeConditions', {'SoftCode2', 'ITI', 'Tup', 'ITI'}, ...
    'OutputActions', [{'SoftCode', 8} opto.AllOff]);

sma = AddState(sma, 'Name', 'ServoOutPunish', ...
    'Timer', S.GUI.ServoReturnTimeout_s, ...
    'StateChangeConditions', {'SoftCode2', nextAfterPunishServo(isNaive), 'Tup', nextAfterPunishServo(isNaive)}, ...
    'OutputActions', [{'SoftCode', 8} opto.AllOff]);

if ~isNaive
    sma = AddState(sma, 'Name', 'PunishITI', ...
        'Timer', punishITI, ...
        'StateChangeConditions', {'Tup', 'ITI'}, ...
        'OutputActions', opto.PunishStart);
end

sma = AddState(sma, 'Name', 'ITI', ...
    'Timer', iti, ...
    'StateChangeConditions', {'Tup', '>exit'}, ...
    'OutputActions', [{'SoftCode', 254, 'HiFi1', 'X', 'BNC1', 0} opto.AllOff]);
end

function nextState = nextAfterSpoutIn(isNaive)
if isNaive
    nextState = 'NaiveWaterDelivery';
else
    nextState = 'ChoiceWindow';
end
end

function nextState = nextAfterPunishServo(isNaive)
if isNaive
    nextState = 'NaivePunishOutcome';
else
    nextState = 'PunishITI';
end
end

function nextState = nextAfterStimulus(probeType)
if probeType == 1
    nextState = 'ITI';
elseif probeType == 2
    nextState = 'ProbeSpoutIn';
else
    nextState = 'SpoutInDelay';
end
end

function sma = addChoiceStates(sma, S, target, opto, isNaive)
if isNaive
    timeoutState = 'ServoOutPunish';
    changeMindTimeoutState = 'ServoOutPunish';
else
    timeoutState = 'PreOutcomeDelayPunish';
    changeMindTimeoutState = 'PreOutcomeDelayPunish';
end
if S.GUI.AllowChangeMind
    wrongState = 'PostLickDelayChangeMind';
else
    wrongState = 'PostLickDelayPunish';
end

sma = AddState(sma, 'Name', 'ChoiceWindow', ...
    'Timer', S.GUI.ChoiceWindow_s, ...
    'StateChangeConditions', {target.CorrectLick, 'PostLickDelayReward', target.IncorrectLick, wrongState, 'Tup', timeoutState}, ...
    'OutputActions', opto.SpoutInStart);

if S.GUI.AllowChangeMind
    sma = AddState(sma, 'Name', 'ChangeMindWindow', ...
        'Timer', S.GUI.ChangeMindWindow_s, ...
        'StateChangeConditions', {target.CorrectLick, 'PostLickDelayReward', 'Tup', changeMindTimeoutState}, ...
        'OutputActions', opto.SpoutInOff);
end
end

function sma = addPostLickDelayStates(sma, S, opto, isNaive)
if isNaive
    rewardState = 'NaiveRewardOutcome';
    punishState = 'ServoOutPunish';
else
    rewardState = 'PreOutcomeDelay';
    punishState = 'PreOutcomeDelayPunish';
end
sma = addPostLickDelayState(sma, S, opto, 'PostLickDelayReward', rewardState);
sma = addPostLickDelayState(sma, S, opto, 'PostLickDelayPunish', punishState);
if S.GUI.AllowChangeMind
    sma = addPostLickDelayState(sma, S, opto, 'PostLickDelayChangeMind', 'ChangeMindWindow');
end
end

function sma = addPostLickDelayState(sma, S, opto, stateName, nextState)
sma = AddState(sma, 'Name', stateName, ...
    'Timer', S.GUI.PostLickDelay_s, ...
    'StateChangeConditions', {'Tup', nextState}, ...
    'OutputActions', opto.SpoutInOff);
end

function sma = addNaiveOutcomeStates(sma, target)
sma = AddState(sma, 'Name', 'NaiveWaterDelivery', ...
    'Timer', target.ValveTime, ...
    'StateChangeConditions', {'Tup', 'ChoiceWindow'}, ...
    'OutputActions', {target.Valve, 1});

sma = AddState(sma, 'Name', 'NaiveRewardOutcome', ...
    'Timer', 0, ...
    'StateChangeConditions', {'Tup', 'PostRewardDelay'}, ...
    'OutputActions', {});

sma = AddState(sma, 'Name', 'NaivePunishOutcome', ...
    'Timer', 0, ...
    'StateChangeConditions', {'Tup', 'ITI'}, ...
    'OutputActions', {});
end

function sma = addTrainedOutcomeStates(sma, S, target, opto)
sma = AddState(sma, 'Name', 'PreOutcomeDelay', ...
    'Timer', S.GUI.PreOutcomeDelay_s, ...
    'StateChangeConditions', {'Tup', 'Reward'}, ...
    'OutputActions', [opto.SpoutInOff opto.PreOutcomeStart]);

sma = AddState(sma, 'Name', 'Reward', ...
    'Timer', target.ValveTime, ...
    'StateChangeConditions', {'Tup', 'PostRewardDelay'}, ...
    'OutputActions', [{target.Valve, 1} opto.RewardStart]);

sma = AddState(sma, 'Name', 'PreOutcomeDelayPunish', ...
    'Timer', S.GUI.PreOutcomeDelay_s, ...
    'StateChangeConditions', {'Tup', 'ServoOutPunish'}, ...
    'OutputActions', [opto.SpoutInOff opto.PreOutcomeStart]);
end

function duration = stimulusOptoDuration(S, stimulusDuration)
duration = S.GUI.PreStimDelay_s + stimulusDuration;
end

function opto = noOptoActions
% Supply empty shared actions without adding opto configuration to naive trials.
opto.Timers = struct([]);
opto.StartActions = {};
opto.StimulusStart = {};
opto.SpoutInDelayStart = {};
opto.SpoutInOff = {};
opto.SpoutInStart = {};
opto.PreOutcomeStart = {};
opto.RewardStart = {};
opto.PostRewardStart = {};
opto.PunishStart = {};
opto.AllOff = {};
end
