function sma = BuildStateMachine(S, optoType, iti)
% Build the minimum opto test state machine.
opto = OptoControl('actions', S, optoType);

sma = NewStateMatrix();
for i = 1:numel(opto.Timers)
    timer = opto.Timers(i);
    sma = SetGlobalTimer(sma, ...
        'TimerID', timer.TimerID, ...
        'Duration', timer.Duration, ...
        'OnsetDelay', 0, ...
        'Channel', timer.Channel, ...
        'OnLevel', timer.OnLevel, ...
        'OffLevel', timer.OffLevel, ...
        'Loop', 0, ...
        'LoopInterval', 0, ...
        'SendGlobalTimerEvents', 0, ...
        'GlobalTimerEvents', 0, ...
        'OffsetValue', 0);
end

sma = AddState(sma, 'Name', 'Start', ...
    'Timer', 0.01, ...
    'StateChangeConditions', {'Tup', 'PreStimDelay'}, ...
    'OutputActions', [{'BNC1', 1, 'SoftCode', 3} opto.Start]);

sma = AddState(sma, 'Name', 'PreStimDelay', ...
    'Timer', S.GUI.PreStimDelay_s, ...
    'StateChangeConditions', {'Tup', 'Image1Display'}, ...
    'OutputActions', [{'SoftCode', 3} opto.PreStimDelay]);

sma = AddState(sma, 'Name', 'Image1Display', ...
    'Timer', S.GUI.ImageDuration_s, ...
    'StateChangeConditions', {'Tup', 'ImageInterval'}, ...
    'OutputActions', [{'SoftCode', 1} opto.Image1Display]);

sma = AddState(sma, 'Name', 'ImageInterval', ...
    'Timer', S.GUI.ImageInterval_s, ...
    'StateChangeConditions', {'Tup', 'Image2Display'}, ...
    'OutputActions', [{'SoftCode', 3} opto.ImageInterval]);

sma = AddState(sma, 'Name', 'Image2Display', ...
    'Timer', S.GUI.ImageDuration_s, ...
    'StateChangeConditions', {'Tup', 'PostStimDelay'}, ...
    'OutputActions', [{'SoftCode', 2} opto.Image2Display]);

sma = AddState(sma, 'Name', 'PostStimDelay', ...
    'Timer', S.GUI.PostStimDelay_s, ...
    'StateChangeConditions', {'Tup', 'ITI'}, ...
    'OutputActions', [{'SoftCode', 3} opto.PostStimDelay]);

sma = AddState(sma, 'Name', 'ITI', ...
    'Timer', iti, ...
    'StateChangeConditions', {'Tup', '>exit'}, ...
    'OutputActions', [{'BNC1', 0, 'SoftCode', 3} opto.ITI]);
end
