function sma = BuildStateMachine(S, delay, trialType, optoType, assistTrial, iti, punishITI)
if trialType == 1
    % Short and long trials can use different press 2 windows.
    press2Window = S.GUI.ShortPress2Window_s;
else
    press2Window = S.GUI.LongPress2Window_s;
end

% Resolve per-trial settings used by the state matrix.
opto = OptoControl('actions', S, optoType, delay, press2Window);

if S.GUI.TimingMode == 1
    cue2OnMessage = 2;
else
    cue2OnMessage = 0;
end

press2StartState = 'PrePress2Delay';
if assistTrial
    % Assisted trials start timing while the lever is still available.
    prePress2DelayTimer = delay;
    prePress2DelayConditions = {'RotaryEncoder1_1', 'Press2', 'Tup', 'Assist'};
    prePress2DelayActions = [{'SoftCode', 19, 'GlobalTimerTrig', '1', 'RotaryEncoder1', 'E'} opto.VisualStimulus1OffActions];
    waitForPress2Timer = max(0, press2Window - delay);
    waitForPress2Actions = {'RotaryEncoder1', 'E'};
else
    prePress2DelayTimer = 0;
    prePress2DelayConditions = {'Tup', 'WaitForPress2'};
    prePress2DelayActions = [{'SoftCode', 12, 'RotaryEncoder1', 'E'} opto.VisualStimulus1OffActions];
    waitForPress2Timer = press2Window;
    waitForPress2Actions = {'SoftCode', 19, 'GlobalTimerTrig', '1'};
end

% Start cue 2 timing from press 2 window onset.
sma = NewStateMatrix();
sma = SetGlobalTimer(sma, 'TimerID', 1, 'Duration', S.GUI.VisualCueDuration_s, 'OnsetDelay', delay, 'Channel', 'SoftCode', 'OnMessage', cue2OnMessage, 'OffMessage', 0);
for i = 1:numel(opto.Timers)
    timer = opto.Timers(i);
    sma = SetGlobalTimer(sma, ...
        'TimerID', timer.TimerID, ...
        'Duration', timer.Duration, ...
        'OnsetDelay', timer.OnsetDelay, ...
        'Channel', timer.Channel, ...
        'OnLevel', timer.OnLevel, ...
        'OffLevel', timer.OffLevel, ...
        'Loop', timer.Loop, ...
        'LoopInterval', timer.LoopInterval, ...
        'SendGlobalTimerEvents', 0, ...
        'GlobalTimerEvents', 0, ...
        'OffsetValue', 0);
end

% Reset encoder, mark BNC, and play cue 1.
sma = AddState(sma, 'Name', 'Start', ...
    'Timer', 0.01, ...
    'StateChangeConditions', {'Tup', 'VisualStimulus1'}, ...
    'OutputActions', [{'BNC1', 1, 'RotaryEncoder1', ['E#' 0]} opto.StartActions]);

if S.GUI.PressMode == 2
    cue1NextState = 'WaitForPress1';
else
    cue1NextState = press2StartState;
end

% Cue 1 ends into either press 1 or directly into press 2.
sma = AddState(sma, 'Name', 'VisualStimulus1', ...
    'Timer', S.GUI.VisualCueDuration_s, ...
    'StateChangeConditions', {'Tup', cue1NextState}, ...
    'OutputActions', [{'SoftCode', 1, 'RotaryEncoder1', 'E'} opto.VisualStimulus1Actions]);

sma = AddState(sma, 'Name', 'WaitForPress1', ...
    'Timer', S.GUI.Press1Window_s, ...
    'StateChangeConditions', {'RotaryEncoder1_1', 'Press1', 'Tup', 'DidNotPress1'}, ...
    'OutputActions', [{'SoftCode', 12} opto.VisualStimulus1OffActions]);

sma = AddState(sma, 'Name', 'Press1', ...
    'Timer', S.GUI.ServoMoveDelay_s, ...
    'StateChangeConditions', {'Tup', 'LeverRetract1'}, ...
    'OutputActions', {});

sma = AddState(sma, 'Name', 'LeverRetract1', ...
    'Timer', S.GUI.ServoReturnTimeout_s, ...
    'StateChangeConditions', {'SoftCode2', press2StartState, 'Tup', press2StartState}, ...
    'OutputActions', [{'SoftCode', 8} opto.LeverRetract1Actions]);

% Press 2 window starts after release, or after assist holding ends.
sma = AddState(sma, 'Name', 'PrePress2Delay', ...
    'Timer', prePress2DelayTimer, ...
    'StateChangeConditions', prePress2DelayConditions, ...
    'OutputActions', prePress2DelayActions);

sma = AddState(sma, 'Name', 'WaitForPress2', ...
    'Timer', waitForPress2Timer, ...
    'StateChangeConditions', {'RotaryEncoder1_1', 'Press2', 'Tup', 'DidNotPress2'}, ...
    'OutputActions', waitForPress2Actions);

sma = AddState(sma, 'Name', 'Assist', ...
    'Timer', 0, ...
    'StateChangeConditions', {'Tup', 'WaitForPress2'}, ...
    'OutputActions', {'SoftCode', 12});

% Press 2 captures timing, returns servo, then routes to outcome.
sma = AddState(sma, 'Name', 'Press2', ...
    'Timer', S.GUI.ServoMoveDelay_s, ...
    'StateChangeConditions', {'Tup', 'RewardLeverRetract'}, ...
    'OutputActions', {'SoftCode', 21, 'GlobalTimerCancel', '1'});

sma = AddState(sma, 'Name', 'RewardLeverRetract', ...
    'Timer', S.GUI.ServoReturnTimeout_s + 0.1, ...
    'StateChangeConditions', {'SoftCode1', 'EarlyPress2', 'SoftCode2', 'PreRewardDelay', 'SoftCode3', 'Press2Late', 'Tup', 'DidNotPress2'}, ...
    'OutputActions', [{'SoftCode', 22} opto.RewardLeverRetractActions]);

sma = AddState(sma, 'Name', 'PreRewardDelay', ...
    'Timer', S.GUI.PreRewardDelay_s, ...
    'StateChangeConditions', {'Tup', 'Reward'}, ...
    'OutputActions', opto.PreRewardDelayActions);

% Reward delivery waits for soft code 3 after dynamic valve control.
sma = AddState(sma, 'Name', 'Reward', ...
    'Timer', 5, ...
    'StateChangeConditions', {'SoftCode3', 'PostRewardDelay', 'Tup', 'PostRewardDelay'}, ...
    'OutputActions', [{'SoftCode', 20} opto.RewardActions]);

sma = AddState(sma, 'Name', 'PostRewardDelay', ...
    'Timer', S.GUI.PostRewardDelay_s, ...
    'StateChangeConditions', {'Tup', 'LeverRetractFinal'}, ...
    'OutputActions', opto.PostRewardDelayActions);

% Terminal states keep outcome names explicit for plotting and analysis.
sma = AddState(sma, 'Name', 'EarlyPress2', 'Timer', 0, 'StateChangeConditions', {'Tup', 'Punish_ITI'}, 'OutputActions', {});
sma = AddState(sma, 'Name', 'Press2Late', 'Timer', 0, 'StateChangeConditions', {'Tup', 'Punish_ITI'}, 'OutputActions', {});
sma = AddState(sma, 'Name', 'DidNotPress1', 'Timer', S.GUI.ServoReturnTimeout_s, 'StateChangeConditions', {'SoftCode2', 'Punish_ITI', 'Tup', 'Punish_ITI'}, 'OutputActions', {'SoftCode', 8});
sma = AddState(sma, 'Name', 'DidNotPress2', 'Timer', S.GUI.ServoReturnTimeout_s, 'StateChangeConditions', {'SoftCode2', 'Punish_ITI', 'Tup', 'Punish_ITI'}, 'OutputActions', {'SoftCode', 18, 'GlobalTimerCancel', '1'});
sma = AddState(sma, 'Name', 'LeverRetractFinal', 'Timer', 0, 'StateChangeConditions', {'Tup', 'ITI'}, 'OutputActions', opto.LeverRetractFinalActions);
sma = AddState(sma, 'Name', 'Punish_ITI', 'Timer', punishITI, 'StateChangeConditions', {'Tup', 'ITI'}, 'OutputActions', {'SoftCode', 0});
sma = AddState(sma, 'Name', 'ITI', 'Timer', iti, 'StateChangeConditions', {'Tup', '>exit'}, 'OutputActions', {'BNC1', 0});
end
