function sma = BuildStateMachine(S, delay, trialType, optoType, assistTrial, iti, punishITI)
% Resolve per-trial settings used by the state matrix.
opto = OptoControl('actions', S, optoType, delay);

if trialType == 1
    press2Window = S.GUI.ShortPress2Window_s;
else
    press2Window = S.GUI.LongPress2Window_s;
end

if S.GUI.TimingMode == 1
    cue2OnMessage = 2;
else
    cue2OnMessage = 0;
end

if assistTrial
    press2StartState = 'AssistHold';
else
    press2StartState = 'ServoRelease2';
end

% Start cue 2 timing from press 2 window onset.
sma = NewStateMatrix();
sma = SetGlobalTimer(sma, 'TimerID', 1, 'Duration', S.GUI.VisualCueDuration_s, 'OnsetDelay', delay, 'Channel', 'SoftCode', 'OnMessage', cue2OnMessage, 'OffMessage', 0);
for i = 1:numel(opto.Timers)
    timer = opto.Timers(i);
    sma = SetGlobalTimer(sma, ...
        'TimerID', timer.TimerID, ...
        'Duration', timer.Duration, ...
        'OnsetDelay', timer.OnsetDelay, ...
        'Channel', timer.Channel, ...
        'OnLevel', timer.OnLevel, ...
        'OffLevel', timer.OffLevel, ...
        'Loop', timer.Loop, ...
        'LoopInterval', timer.LoopInterval, ...
        'SendGlobalTimerEvents', 0, ...
        'GlobalTimerEvents', 0, ...
        'OffsetValue', 0);
end

% Reset encoder, mark BNC, and play cue 1.
sma = AddState(sma, 'Name', 'Start', ...
    'Timer', 0.01, ...
    'StateChangeConditions', {'Tup', 'VisualCue1'}, ...
    'OutputActions', {'BNC1', 1, 'RotaryEncoder1', ['E#' 0]});

if S.GUI.PressMode == 2
    cue1NextState = 'ServoRelease1';
else
    cue1NextState = press2StartState;
end

% Cue 1 ends into either press 1 or directly into press 2.
sma = AddState(sma, 'Name', 'VisualCue1', ...
    'Timer', S.GUI.VisualCueDuration_s, ...
    'StateChangeConditions', {'Tup', cue1NextState}, ...
    'OutputActions', [{'SoftCode', 1, 'RotaryEncoder1', 'E'} opto.VisualCue1Actions]);

sma = AddState(sma, 'Name', 'ServoRelease1', ...
    'Timer', 0, ...
    'StateChangeConditions', {'Tup', 'WaitForPress1'}, ...
    'OutputActions', {'SoftCode', 12});

sma = AddState(sma, 'Name', 'WaitForPress1', ...
    'Timer', S.GUI.Press1Window_s, ...
    'StateChangeConditions', {'RotaryEncoder1_1', 'Press1', 'Tup', 'ServoBackNoPress1'}, ...
    'OutputActions', {});

sma = AddState(sma, 'Name', 'Press1', ...
    'Timer', S.GUI.ServoMoveDelay_s, ...
    'StateChangeConditions', {'Tup', 'ServoBack1'}, ...
    'OutputActions', {});

sma = AddState(sma, 'Name', 'ServoBack1', ...
    'Timer', S.GUI.ServoReturnTimeout_s, ...
    'StateChangeConditions', {'SoftCode2', press2StartState, 'Tup', press2StartState}, ...
    'OutputActions', [{'SoftCode', 8} opto.ServoBack1Actions]);

sma = AddState(sma, 'Name', 'ServoBackNoPress1', ...
    'Timer', S.GUI.ServoReturnTimeout_s, ...
    'StateChangeConditions', {'SoftCode2', 'DidNotPress1', 'Tup', 'DidNotPress1'}, ...
    'OutputActions', {'SoftCode', 8});

% Press 2 window starts after release, or after assist holding ends.
sma = AddState(sma, 'Name', 'ServoRelease2', ...
    'Timer', 0, ...
    'StateChangeConditions', {'Tup', 'WaitForPress2'}, ...
    'OutputActions', {'SoftCode', 12, 'RotaryEncoder1', 'E'});

sma = AddState(sma, 'Name', 'WaitForPress2', ...
    'Timer', press2Window, ...
    'StateChangeConditions', {'RotaryEncoder1_1', 'Press2', 'Tup', 'ServoBackNoPress2'}, ...
    'OutputActions', {'SoftCode', 19, 'GlobalTimerTrig', '1'});

sma = AddState(sma, 'Name', 'AssistHold', ...
    'Timer', delay, ...
    'StateChangeConditions', {'RotaryEncoder1_1', 'Press2', 'Tup', 'AssistRelease'}, ...
    'OutputActions', {'SoftCode', 19, 'GlobalTimerTrig', '1', 'RotaryEncoder1', 'E'});

sma = AddState(sma, 'Name', 'AssistRelease', ...
    'Timer', 0, ...
    'StateChangeConditions', {'Tup', 'AssistWaitForPress2'}, ...
    'OutputActions', {'SoftCode', 12});

sma = AddState(sma, 'Name', 'AssistWaitForPress2', ...
    'Timer', max(0, press2Window - delay), ...
    'StateChangeConditions', {'RotaryEncoder1_1', 'Press2', 'Tup', 'ServoBackNoPress2'}, ...
    'OutputActions', {'RotaryEncoder1', 'E'});

% Press 2 captures timing, returns servo, then routes to outcome.
sma = AddState(sma, 'Name', 'Press2', ...
    'Timer', S.GUI.ServoMoveDelay_s, ...
    'StateChangeConditions', {'Tup', 'ServoBack2'}, ...
    'OutputActions', {'SoftCode', 21, 'GlobalTimerCancel', '1'});

sma = AddState(sma, 'Name', 'ServoBack2', ...
    'Timer', S.GUI.ServoReturnTimeout_s + 0.1, ...
    'StateChangeConditions', {'SoftCode1', 'Press2Early', 'SoftCode2', 'RewardDelay', 'SoftCode3', 'Press2Late', 'Tup', 'DidNotPress2'}, ...
    'OutputActions', {'SoftCode', 22});

sma = AddState(sma, 'Name', 'ServoBackNoPress2', ...
    'Timer', S.GUI.ServoReturnTimeout_s, ...
    'StateChangeConditions', {'SoftCode2', 'DidNotPress2', 'Tup', 'DidNotPress2'}, ...
    'OutputActions', {'SoftCode', 18, 'GlobalTimerCancel', '1'});

% Reward amount is computed in the soft-code handler.
sma = AddState(sma, 'Name', 'RewardDelay', ...
    'Timer', S.GUI.RewardDelay_s, ...
    'StateChangeConditions', {'Tup', 'Reward'}, ...
    'OutputActions', opto.RewardDelayActions);

sma = AddState(sma, 'Name', 'Reward', ...
    'Timer', 5, ...
    'StateChangeConditions', {'SoftCode3', 'PostRewardDelay', 'Tup', 'PostRewardDelay'}, ...
    'OutputActions', {'SoftCode', 20});

sma = AddState(sma, 'Name', 'PostRewardDelay', ...
    'Timer', S.GUI.PostRewardDelay_s, ...
    'StateChangeConditions', {'Tup', 'OutcomeReward'}, ...
    'OutputActions', {});

% Terminal states keep outcome names explicit for plotting and analysis.
sma = AddState(sma, 'Name', 'Press2Early', 'Timer', 0, 'StateChangeConditions', {'Tup', 'PunishITI'}, 'OutputActions', {});
sma = AddState(sma, 'Name', 'Press2Late', 'Timer', 0, 'StateChangeConditions', {'Tup', 'PunishITI'}, 'OutputActions', {});
sma = AddState(sma, 'Name', 'DidNotPress1', 'Timer', 0, 'StateChangeConditions', {'Tup', 'PunishITI'}, 'OutputActions', {});
sma = AddState(sma, 'Name', 'DidNotPress2', 'Timer', 0, 'StateChangeConditions', {'Tup', 'PunishITI'}, 'OutputActions', {});
sma = AddState(sma, 'Name', 'OutcomeReward', 'Timer', 0, 'StateChangeConditions', {'Tup', 'ITI'}, 'OutputActions', {});
sma = AddState(sma, 'Name', 'PunishITI', 'Timer', punishITI, 'StateChangeConditions', {'Tup', 'ITI'}, 'OutputActions', {'SoftCode', 0});
sma = AddState(sma, 'Name', 'ITI', 'Timer', iti, 'StateChangeConditions', {'Tup', '>exit'}, 'OutputActions', {'BNC1', 0});
end
