function StateWellTrained(S, CorrectPort, IncorrectPort, CorrectLick, IncorrectLick, OutputActionArgInitCue, ...
    CenterValveTime, visStim, audStim, ...
    VisStimDuration, wait_dur, OutputActionsPreGoCueDelay, ...
    OutputActionsEarlyChoice, OutputActionArgGoCue, ValveTime, Valve, ...
    OutputActionsPunishSetup, OutputActionArgIncorrect, TimeOutPunish, ITI)

    sma = NewStateMatrix(); % Assemble state matrix
    sma = SetCondition(sma, 1, CorrectPort, 1); % Condition 1: Correct Port is high (licking)
    sma = SetCondition(sma, 2, IncorrectPort, 1); % Condition 2: Incorrect Port is high (licking)
    sma = SetCondition(sma, 3, 'Port4', 1); % Condition 3: Sync signal high
    sma = SetCondition(sma, 4, 'Port4', 0); % Condition 4: Sync signal low
    sma = SetCondition(sma, 5, 'Port2', 1); % Condition 5: center port is high (licking)

    sma = AddState(sma, 'Name', 'Start', ...
        'Timer', 0.080,...
        'StateChangeConditions', {'Tup', 'InitCue'},...
        'OutputActions', {'HiFi1','*', 'BNC1', 1});

    sma = AddState(sma, 'Name', 'InitCue', ...
        'Timer', S.GUI.InitCueDuration_s,...
        'StateChangeConditions', {'Tup', 'InitWindow'},...         
        'OutputActions', OutputActionArgInitCue);

    sma = AddState(sma, 'Name', 'InitReward', ...
        'Timer', CenterValveTime,...
        'StateChangeConditions', {'Tup', 'InitWindow'},...
        'OutputActions', {'Valve2', 1});

    sma = AddState(sma, 'Name', 'InitWindow', ...
        'Timer', S.GUI.InitWindowTimeout_s,...
        'StateChangeConditions', {'Tup', 'InitCueAgain', 'Port2In', 'PreVisStimDelay', 'Port1In', 'WrongInitiation', 'Port3In', 'WrongInitiation'},...         
        'OutputActions', {});

    sma = AddState(sma, 'Name', 'InitCueAgain', ...
        'Timer', 0,...
        'StateChangeConditions', {'Tup', 'InitCue'},...         
        'OutputActions', {});

    sma = AddState(sma, 'Name', 'WrongInitiation', ...
        'Timer', 0,...
        'StateChangeConditions', {'Tup', 'TimeOutPunish'},...         
        'OutputActions', {});     

    sma = AddState(sma, 'Name', 'PreVisStimDelay', ...
        'Timer', S.GUI.PreVisStimDelay_s,...
        'StateChangeConditions', {'Tup', 'VisStimTrigger'},...
        'OutputActions', {});    

    sma = AddState(sma, 'Name', 'VisStimTrigger', ...
        'Timer', 0,...
        'StateChangeConditions', {'BNC1High', 'AudStimTrigger'},...
        'OutputActions', visStim);

    sma = AddState(sma, 'Name', 'AudStimTrigger', ...
        'Timer', wait_dur,...
        'StateChangeConditions', {'Tup', 'VisualStim_AllowedSideLick', 'Port1In', 'EarlyChoice', 'Port3In', 'EarlyChoice'},...
        'OutputActions', audStim);

    sma = AddState(sma, 'Name', 'VisualStim_AllowedSideLick', ...
        'Timer', VisStimDuration - wait_dur,...
        'StateChangeConditions', {'Tup', 'CenterReward'},...
        'OutputActions', {});

    sma = AddState(sma, 'Name', 'CenterReward', ...
        'Timer', CenterValveTime,...
        'StateChangeConditions', {'Tup', 'PreGoCueDelay'},...
        'OutputActions', {'Valve2', 1, 'SoftCode', 255});    

    sma = AddState(sma, 'Name', 'PreGoCueDelay', ...
        'Timer', S.GUI.PreGoCueDelay_s,...
        'StateChangeConditions', {'Tup', 'GoCue'},...         
        'OutputActions', OutputActionsPreGoCueDelay);   

    sma = AddState(sma, 'Name', 'EarlyChoice', ...
        'Timer', 0,...
        'StateChangeConditions', {'Tup', 'TimeOutPunish'},...
        'OutputActions', OutputActionsEarlyChoice);

    sma = AddState(sma, 'Name', 'GoCue', ...
        'Timer', S.GUI.GoCueDuration_s,...
        'StateChangeConditions', {'Tup', 'WindowChoice'},...         
        'OutputActions', OutputActionArgGoCue);      
    
    sma = AddState(sma, 'Name', 'ExtraStimDurPostRew_Naive', ...
        'Timer', S.GUI.ExtraStimDurPostRew_Naive_s,...
        'StateChangeConditions', {'Tup', 'ITI'},...
        'OutputActions', {});
    
    sma = AddState(sma, 'Name', 'WindowChoice', ...
        'Timer', S.GUI.ChoiceWindow_s,...
        'StateChangeConditions', {CorrectLick, 'CorrectLickInterval', 'Condition1', 'CorrectLickInterval', IncorrectLick, 'IncorrectLickInterval', 'Condition2', 'IncorrectLickInterval', 'Tup', 'DidNotChoose'},...
        'OutputActions', {'HiFi1', 'X'});        

    sma = AddState(sma, 'Name', 'DidNotChoose', ...
        'Timer', 0,...
        'StateChangeConditions', {'Tup', 'TimeOutPunish'},...
        'OutputActions', {});   

    sma = AddState(sma, 'Name', 'CorrectLickInterval', ...
        'Timer', S.GUI.ConfirmLickInterval_s,...
        'StateChangeConditions', {'Tup', 'WindowCorrectChoiceConfirm', IncorrectLick, 'IncorrectLickInterval'},...
        'OutputActions', {});

    sma = AddState(sma, 'Name', 'IncorrectLickInterval', ...
        'Timer', S.GUI.ConfirmLickInterval_s,...
        'StateChangeConditions', {'Tup', 'WindowIncorrectChoiceConfirm', CorrectLick, 'CorrectLickInterval'},...
        'OutputActions', {});

    sma = AddState(sma, 'Name', 'WindowCorrectChoiceConfirm', ...
        'Timer', S.GUI.ChoiceConfirmWindow_s,...
        'StateChangeConditions', {'Tup', 'DidNotConfirm', CorrectLick, 'RewardDelay', IncorrectLick, 'IncorrectLickInterval', 'Condition1', 'RewardDelay', 'Condition2', 'IncorrectLickInterval'},...
        'OutputActions', {});

    sma = AddState(sma, 'Name', 'WindowIncorrectChoiceConfirm', ...
        'Timer', S.GUI.ChoiceConfirmWindow_s,...
        'StateChangeConditions', {'Tup', 'DidNotConfirm', CorrectLick, 'CorrectLickInterval', IncorrectLick, 'PunishSetup', 'Condition1', 'CorrectLickInterval', 'Condition2', 'PunishSetup'},...
        'OutputActions', {});

    sma = AddState(sma, 'Name', 'DidNotConfirm', ...
        'Timer', 0,...
        'StateChangeConditions', {'Tup', 'TimeOutPunish'},...
        'OutputActions', {});

    sma = AddState(sma, 'Name', 'RewardDelay', ...
        'Timer', S.GUI.RewardDelay_s,...
        'StateChangeConditions', {'Tup', 'Reward'},...
        'OutputActions', {});

    sma = AddState(sma, 'Name', 'Reward', ...
        'Timer', ValveTime,...
        'StateChangeConditions', {'Tup', 'ExtraStimDurPostRew_Naive'},...
        'OutputActions', {Valve, 1});
  
    sma = AddState(sma, 'Name', 'PunishSetup', ...
        'Timer', 0,...
        'StateChangeConditions', {'Tup', 'Punish'},...
        'OutputActions', OutputActionsPunishSetup); % Set white noise waveform

    sma = AddState(sma, 'Name', 'Punish', ...
        'Timer', S.GUI.PunishSoundDuration_s,...
        'StateChangeConditions', {'Tup', 'TimeOutPunish'},...
        'OutputActions', OutputActionArgIncorrect);

    sma = AddState(sma, 'Name', 'TimeOutPunish', ...
        'Timer', TimeOutPunish,...
        'StateChangeConditions', {'Tup', 'ITI'},...
        'OutputActions', {});

    sma = AddState(sma, 'Name', 'ITI', ...
        'Timer', ITI,...
        'StateChangeConditions', {'Tup', '>exit'},...
        'OutputActions', {'SoftCode', 254, 'HiFi1', 'X'});   
    SendStateMachine(sma); % Send the state matrix to the Bpod device
end