function StatePassive(S, visStim, audStim, VisStimDuration, ITI)

    sma = NewStateMatrix(); % Assemble state matrix
    sma = SetCondition(sma, 3, 'Port4', 1); % Condition 3: Sync signal high
    sma = SetCondition(sma, 4, 'Port4', 0); % Condition 4: Sync signal low

    sma = AddState(sma, 'Name', 'Start', ...
        'Timer', 0.001,...
        'StateChangeConditions', {'Tup', 'VisStimTrigger'},...
        'OutputActions', {'HiFi1','*', 'BNC1', 1});

    sma = AddState(sma, 'Name', 'VisStimTrigger', ...
        'Timer', 0,...
        'StateChangeConditions', {'BNC1High', 'AudStimTrigger'},...
        'OutputActions', visStim);

    sma = AddState(sma, 'Name', 'AudStimTrigger', ...
        'Timer', 0,...
        'StateChangeConditions', {'Tup', 'Passive_VisualStim'},...
        'OutputActions', audStim);

    sma = AddState(sma, 'Name', 'Passive_VisualStim', ...
        'Timer', VisStimDuration,...
        'StateChangeConditions', {'Tup', 'ExtraStimDurPostRew_Naive'},...
        'OutputActions', {});

    sma = AddState(sma, 'Name', 'ExtraStimDurPostRew_Naive', ...
        'Timer', S.GUI.ExtraStimDurPostRew_Naive_s,...
        'StateChangeConditions', {'Tup', 'ITI'},...
        'OutputActions', {});

    sma = AddState(sma, 'Name', 'ITI', ...
        'Timer', ITI,...
        'StateChangeConditions', {'Tup', '>exit'},...
        'OutputActions', {'SoftCode', 254, 'HiFi1', 'X'});   
    SendStateMachine(sma); % Send the state matrix to the Bpod device
end