function StatePassive(S, SCOA, VisStimDuration, ITI)

    sma = NewStateMatrix();
    sma = SetCondition(sma, 3, 'Port4', 1);
    sma = SetCondition(sma, 4, 'Port4', 0);

    sma = AddState(sma, 'Name', 'Start', ...
        'Timer', 0.068,...
        'StateChangeConditions', {'Tup', 'VisStimTrigger'},...
        'OutputActions', SCOA.Start);

    sma = AddState(sma, 'Name', 'VisStimTrigger', ...
        'Timer', 0,...
        'StateChangeConditions', {'BNC1High', 'Passive_VisualStim'},...
        'OutputActions', SCOA.VisStim);

    sma = AddState(sma, 'Name', 'Passive_VisualStim', ...
        'Timer', VisStimDuration,...
        'StateChangeConditions', {'Tup', 'ITI'},...
        'OutputActions', {});

    sma = AddState(sma, 'Name', 'ITI', ...
        'Timer', ITI,...
        'StateChangeConditions', {'Tup', '>exit'},...
        'OutputActions', {'SoftCode', 254, 'HiFi1', 'X'});

    SendStateMachine(sma);

end